name: 'facebook_pages'
version: '1.2.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<3.0.0"]
vars:
  posts: "{{ source('facebook_pages', 'post_history') }}"
  pages: "{{ source('facebook_pages', 'page') }}"
  post_metrics: "{{ source('facebook_pages', 'lifetime_post_metrics_total') }}"
  page_metrics: "{{ source('facebook_pages', 'daily_page_metrics_total') }}"
models:
  facebook_pages:
    +schema: facebook_pages
    +materialized: table
    staging:
      +schema: stg_facebook_pages
      +materialized: table
      tmp:
        +materialized: view
