name: 'facebook_pages_integration_tests'
version: '1.2.0'
profile: 'integration_tests'
config-version: 2

vars:
  facebook_pages:
    facebook_pages_daily_page_metrics_total_identifier: "facebook_pages_daily_page_metrics_total_data"
    facebook_pages_lifetime_post_metrics_total_identifier: "facebook_pages_lifetime_post_metrics_total_data"
    facebook_pages_page_identifier: "facebook_pages_page_data"
    facebook_pages_post_history_identifier: "facebook_pages_post_history_data"
    facebook_pages_schema: facebook_pages_integrations_tests

models:
  +persist_docs:
    relation: true
    columns: "{{ false if target.type in ('databricks') else true }}"
  facebook_pages:
    +schema: "facebook_pages_{{ var('directed_schema','dev') }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +docs:
    show: False
  facebook_pages_integration_tests:
    facebook_pages_post_history_data:
      +column_types:
        id: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        promotable_id: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        page_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    facebook_pages_lifetime_post_metrics_total_data:
      +column_types:
        post_id: "{{ 'string' if target.type in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        post_media_view: float
    facebook_pages_page_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    facebook_pages_daily_page_metrics_total_data:
      +column_types:
        page_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        page_media_view: float
flags:
  send_anonymous_usage_stats: False
  use_colors: True